-- Tabla VINO 
 

CREATE TABLE VINO ( 

  CODIGO_VINO NUMBER(10) NOT NULL PRIMARY KEY, 

  DESCRIPCION VARCHAR2(50) NOT NULL, 

  CATEGORIA VARCHAR2(20) NOT NULL, 

  AÑO_ELABOR NUMBER(4) NOT NULL, 

  BODEGA NUMBER(10) NOT NULL,  -- Change data type to match BODEGA.CODIGO_BODEGA 

  CONSTRAINT FK_VINO_BODEGA FOREIGN KEY (BODEGA) REFERENCES BODEGA(CODIGO_BODEGA) 

); 

 
 
-- Tabla PEDIDO 
CREATE TABLE PEDIDO ( 
  CODIGO_PEDIDO NUMBER(10) NOT NULL PRIMARY KEY, 
  CODIGO_VINO NUMBER(10) NOT NULL REFERENCES VINO(CODIGO_VINO), 
  CODIGO_PROV NUMBER(10) NOT NULL REFERENCES PROVEEDOR(CODIGO_PROV), 
  CODIGO_CLI NUMBER(10) NOT NULL REFERENCES CLIENTE(CODIGO_CLI), 
  FECHA DATE NOT NULL, 
  CANTIDAD NUMBER(10) NOT NULL, 
  PRECIO_UNIT NUMBER(10,2) NOT NULL 
); 
 
-- Tabla PROVEEDOR 
CREATE TABLE PROVEEDOR ( 
  CODIGO_PROV NUMBER(10) NOT NULL PRIMARY KEY, 
  RAZON_SOCIAL VARCHAR2(50) NOT NULL 
); 
 
-- Tabla CLIENTE 
CREATE TABLE CLIENTE ( 
  CODIGO_CLI NUMBER(10) NOT NULL PRIMARY KEY, 
  CATEGORIA VARCHAR2(20) NOT NULL, 
  NOM_RAZON VARCHAR2(50) NOT NULL, 
  TELEFONO VARCHAR2(20), 
  EMAIL VARCHAR2(50) 
); 
 
-- Tabla COMPRA 
CREATE TABLE COMPRA ( 
  CODIGO_COMPRA NUMBER(10) NOT NULL PRIMARY KEY, 
  CODIGO_VINO NUMBER(10) NOT NULL REFERENCES VINO(CODIGO_VINO), 
  CODIGO_CLI NUMBER(10) NOT NULL REFERENCES CLIENTE(CODIGO_CLI), 
  FECHA DATE NOT NULL, 
  CANTIDAD NUMBER(10) NOT NULL, 
  PRECIO_UNIT NUMBER(10,2) NOT NULL 
); 
 
-- Tabla CATEGORIA 
CREATE TABLE CATEGORIA ( 
  CODIGO NUMBER(10) NOT NULL PRIMARY KEY, 
  DESCRIPCION VARCHAR2(20) NOT NULL 
); 
 
-- Tabla CATEGORIA_PROVEEDOR 
CREATE TABLE CATEGORIA_PROVEEDOR ( 
  CODIGO_PROV NUMBER(10) NOT NULL REFERENCES PROVEEDOR(CODIGO_PROV), 
  CODIGO_CATEGORIA NUMBER(10) NOT NULL REFERENCES CATEGORIA(CODIGO), 
  CANTIDAD NUMBER(10) NOT NULL, 
  FACTURACION VARCHAR2(20), 
  VENTAS NUMBER(10) NOT NULL, 
  PRIMARY KEY (CODIGO_PROV, CODIGO_CATEGORIA) 
); 
 
-- Tabla BODEGA 
CREATE TABLE BODEGA ( 
  CODIGO_BODEGA NUMBER(10) NOT NULL PRIMARY KEY, 
  DESCRIPCION VARCHAR2(50) NOT NULL 
);